# primary
background = #1a1b26
foreground = #ffffff

cursor-color = #bb9af7
cursor-text = #1a1b26

# normal colors
palette = 0=#414868
palette = 1=#ff7a93
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#7da6ff
palette = 5=#bb9af7
palette = 6=#0db9d7
palette = 7=#c0caf5

# bright colors
palette = 8=#565f89
palette = 9=#ff7a93
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#7da6ff
palette = 13=#bb9af7
palette = 14=#73daca
palette = 15=#ffffff
