#!/bin/bash

touch /tmp/lid_up

# Get number of connected outputs  
output_count=$(swaymsg -t get_outputs | jq 'length')

if [ "$output_count" -gt 1 ]; then
  swaymsg output eDP-1 enable
  swaymsg output DP-1 scale 1.0 pos 3840 0 res 3840x2160@144Hz
  swaymsg output DP-2 scale 1.0 pos 3840 0 res 3840x2160@144Hz
  swaymsg output DP-3 scale 1.0 pos 3840 0 res 3840x2160@144Hz
fi