#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# Kill already running process
_ps=(waybar swaync xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &

# xdg desktop wlr thing for screen sharing
/usr/lib/xdg-desktop-portal --replace &

~/.config/sway/scripts/swayidle.sh &

~/.bin/wallpaper &
~/.config/sway/scripts/wallpaper_timer &
