# vhs80 theme for swaylock

daemonize
show-failed-attempts

# Background
color=121212
image=~/.config/themes/current/background
scaling=fill

# Indicator
indicator
indicator-radius=120
indicator-thickness=10

# Ring colors
ring-color=8a8a8d
key-hl-color=C6B441
bs-hl-color=C73838

# Inside colors
inside-color=121212
text-color=C6B441

# Separator color
separator-color=00000000

# Verification colors
inside-ver-color=277D46
ring-ver-color=277D46
text-ver-color=eaeaea

# Wrong password colors
inside-wrong-color=862020
ring-wrong-color=C73838
text-wrong-color=eaeaea

# Clear colors
inside-clear-color=A85511
ring-clear-color=E07924
text-clear-color=121212

# Caps lock colors
caps-lock-key-hl-color=46BEBE
caps-lock-bs-hl-color=C73838

font="monospace"
font-size=24
effect-blur=10x3

# Clock display
clock
timestr=%H:%M
datestr=%A, %B %d

# Vignette effect
effect-vignette=0.5:0.5
