# Background and foreground colors
background = #060d1f
foreground = #E0F7FA

cursor-color = #6488EA
cursor-text = #060d1f

selection-background = #d7ebe9
selection-foreground = #374cb3

# Standard colors
palette = 0=#060d1f
palette = 1=#e95c4b
palette = 2=#6488EA
palette = 3=#d5edeb
palette = 4=#f7c3c6
palette = 5=#85cec4
palette = 6=#fff6d2
palette = 7=#e1e9f5

# Bright colors
palette = 8=#51688E
palette = 9=#ed7b6d
palette = 10=#819fee
palette = 11=#d7ebe9
palette = 12=#f2c8cb
palette = 13=#8cc7bf
palette = 14=#fef4d7
palette = 15=#c8cbd0
