-- Generated by hypr2lua-web.
-- Source: hyprland.conf

local activeBorderColor = {
  colors = { "rgba(d7ebe9ee)", "rgba(f2c8cbee)" },
  angle = 45,
}
local inactiveBorderColor = "rgba(51688e99)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
      border_locked_active = activeBorderColor,
      border_locked_inactive = inactiveBorderColor,
    },
    groupbar = {
      font_size = 12,
      font_family = "monospace",
      font_weight_active = "ultraheavy",
      font_weight_inactive = "normal",
      indicator_height = 0,
      indicator_gap = 5,
      height = 22,
      gaps_in = 5,
      gaps_out = 0,
      col = {
        active = "rgba(f7c3c6ff)",
        inactive = "rgba(51688e55)",
      },
      text_color = "rgb(060d1f)",
      text_color_inactive = "rgba(e0f7faaa)",
      gradients = true,
      gradient_rounding = 0,
      gradient_round_only_edges = false,
    },
  },
  decoration = {
    shadow = {
      enabled = true,
      render_power = 4,
      range = 16,
      color = "rgba(5, 5, 5, .7)",
    },
    blur = {
      enabled = true,
      size = 3,
      passes = 2,
    },
  },
})
