# Sapphire theme for Sway

# Color definitions
set $bg #060d1f
set $fg #E0F7FA
set $inactive #51688E
set $red #e95c4b
set $green #6488EA
set $ice #d7ebe9
set $rose #f7c3c6
set $mint #85cec4
set $cream #fff6d2

# Window colors           border      bg          text        indicator   child_border
client.focused            $ice        $bg         $fg         $rose       $ice
client.focused_inactive   $inactive   $bg         $fg         $inactive   $inactive
client.unfocused          $inactive   $bg         $fg         $inactive   $inactive
client.urgent             $red        $bg         $fg         $red        $red
client.placeholder        $inactive   $bg         $fg         $inactive   $inactive
client.background         $bg

# SwayFX-specific settings
shadows enable
shadows_on_csd enable
shadow_blur_radius 16
shadow_color #05050599

blur enable
blur_passes 2
blur_radius 3
