# Sapphire theme for swaylock

daemonize
show-failed-attempts

# Background
color=060d1f
image=~/.config/themes/current/background
scaling=fill

# Indicator
indicator
indicator-radius=120
indicator-thickness=10

# Ring colors
ring-color=51688E
key-hl-color=6488EA
bs-hl-color=e95c4b

# Inside colors
inside-color=060d1f
text-color=d7ebe9

# Separator color
separator-color=00000000

# Verification colors
inside-ver-color=85cec4
ring-ver-color=85cec4
text-ver-color=060d1f

# Wrong password colors
inside-wrong-color=e95c4b
ring-wrong-color=e95c4b
text-wrong-color=E0F7FA

# Clear colors
inside-clear-color=f7c3c6
ring-clear-color=f7c3c6
text-clear-color=060d1f

# Caps lock colors
caps-lock-key-hl-color=fff6d2
caps-lock-bs-hl-color=e95c4b

font="monospace"
font-size=24
effect-blur=10x3

# Clock display
clock
timestr=%H:%M
datestr=%A, %B %d

# Vignette effect
effect-vignette=0.5:0.5
