# Background and foreground colors
background = #2d2940
foreground = #6096fd

# Standard colors
palette = 0=#2d2940
palette = 1=#C0685F
palette = 2=#965f81
palette = 3=#fca766
palette = 4=#7b79a4
palette = 5=#987195
palette = 6=#7c79a5
palette = 7=#6096fd

# Bright colors
palette = 8=#684764
palette = 9=#ee897d
palette = 10=#bb90a1
palette = 11=#ffd46b
palette = 12=#a09bd3
palette = 13=#c192c0
palette = 14=#a19bd4
palette = 15=#00ffd2
