background            #2d2940
foreground            #6096fd

# black
color0  #2d2940
color8  #684764

# red
color1  #C0685F
color9  #ee897d

# green
color2  #965f81
color10 #bb90a1

# yellow
color3  #fca766
color11 #ffd46b

# blue
color4  #7b79a4
color12 #a09bd3

# magenta
color5  #987195
color13 #c192c0

#cyan
color6  #7c79a5
color14 #a19bd4

#white
color7  #6096fd
color15 #00ffd2


