# Moon Orbit theme for Sway

# Color definitions
set $bg #2d2940
set $fg #6096fd
set $inactive #684764
set $lighter #423e53
set $red #C0685F
set $orange #fca766
set $blue #7b79a4
set $purple #987195
set $accent #a09bd3

# Window colors           border      bg          text        indicator   child_border
client.focused            $blue       $bg         $fg         $accent     $blue
client.focused_inactive   $inactive   $bg         $fg         $inactive   $inactive
client.unfocused          $inactive   $bg         $fg         $inactive   $inactive
client.urgent             $red        $bg         $fg         $red        $red
client.placeholder        $inactive   $bg         $fg         $inactive   $inactive
client.background         $bg

# SwayFX-specific settings
shadows enable
shadows_on_csd enable
shadow_blur_radius 20
shadow_color #00000088

blur enable
blur_passes 2
blur_radius 5
