# primary
background = #000000
foreground = #E0E0E0

cursor-color = #00BFFF
cursor-text = #000000

selection-background = #333333
selection-foreground = cell-foreground

# normal colors
palette = 0=#000000
palette = 1=#FF0040
palette = 2=#00BFFF
palette = 3=#1E90FF
palette = 4=#00BFFF
palette = 5=#1E90FF
palette = 6=#00BFFF
palette = 7=#E0E0E0

# bright colors
palette = 8=#1A1A1A
palette = 9=#FF0040
palette = 10=#00BFFF
palette = 11=#1E90FF
palette = 12=#00BFFF
palette = 13=#1E90FF
palette = 14=#00BFFF
palette = 15=#FFFFFF
