#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## Manage other monitors when lapton lid is open/close
## Edit according to your setup

LID="`ls /proc/acpi/button/lid | head -n1`"
OUTPUT="eDP-1"
echo $LID
echo $OUTPUT

if grep -q open /proc/acpi/button/lid/${LID}/state; then
  hyprctl keyword monitor "eDP-1,2880x1800,0x0,1.5"
else
  hyprctl keyword monitor "eDP-1, disable"
fi
