#!/usr/bin/env bash

# determines if the lid is open or closed, and then sets the laptop monitor accordingly
# this script is run on system resume

LID="`ls /proc/acpi/button/lid | head -n1`"
OUTPUT="eDP-1"
echo $LID
echo $OUTPUT

if grep -q open /proc/acpi/button/lid/${LID}/state; then
  hyprctl keyword monitor "eDP-1,2880x1800,0x0,1.5"
else
  hyprctl keyword monitor "eDP-1, disable"
fi
