#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# Kill already running process
_ps=(waybar dunst xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &

# xdg desktop wlr thing for screen sharing
/usr/lib/xdg-desktop-portal-wlr &

# Lauch notification daemon (mako)
swaync &

# Start network manager applet
nm-applet --indicator &
gammastep-indicator &
~/.config/hypr/scripts/launch_waybar &
waybar -c ~/.config/hypr/waybar/config -s ~/.config/hypr/waybar/style.css &

hypridle &
~/.config/hypr/scripts/wallpaper_shuffle.sh &
